services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/AlexInnovation/n8n-render
    dockerCommand: ""
    image:
      repository: docker.n8n.io/n8nio/n8n
    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: WEBHOOK_URL
        value: https://n8n-atops.onrender.com
  - name: n8n-postgres
    databaseName: n8n
    user: n8n
